### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by amaya-projects** [balkanpy/gw2dps#5]

**Comment by Hech** [comment]
It does for me. Check if [this](https://github.com/balkanpy/gw2dps/issues/3) previous thread helps you

**Comment by amaya-projects** [comment]
I tried using activepython and running gw2dps.py from cmd prompt the program starts but displays 0 target health and dps display.

Date: Tue, 16 Sep 2014 16:38:48 -0700

**Comment by alayja** [comment]
Hey there :) this is an awesome addon, but I'm having a little bit of trouble with it, the EXE files don't work for me either. The program runs but shows 0 on the numbers. 

I've downloaded python and tried running the source files, I still get 0 numbers, until I run GW2 as admin. When I do it briefly shows a command dialog with errors before closing. This is what the error message somewhat looks like, I am unable to copy/paste it before it closes. I'm assuming it's supposed to work after running GW2 as admin, however this error is what's keeping it from working. Any help would be appreciated. Thank you very much :)

Traceback (most recent call last):
       File "C:\Users....\gw2dps.py", line 414, in (...
           app = Main(config_file)
       File "C:\Users....\gw2dps.py", line 202, in (...
           self ._dmg = DamageMeter(ms=self ._ms)
       File "C:\Users....\gw2dps.py", line 66, in (...
           self ._possible_targets = (self.gw2base + TARGET_HEALTH_BASE,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
